#!/usr/bin/env python3
"""Render the Copilot-lane agent definitions as VS Code custom chat modes.

Copilot agent mode reads none of `.claude/` -- not the agent definitions, not
`settings.json`, not the PreToolUse hook. Its nearest equivalent to a subagent
is a chat mode in `.github/chatmodes/`. So the same source has to be rendered
twice, and this script is the second rendering.

**Why the output is gitignored.** `.github/` is committed, and the real agent
definitions are proprietary -- AGENTS.md's "never commit real agent-config
content" rule applies to this rendering exactly as it does to
`.claude/agents/`. The generated modes are therefore gitignored alongside it,
and this script is the only thing that writes them.

Lane is read from the prompt body rather than passed in, so a role that
changes lane upstream changes what gets generated here with no edit to this
file. A definition that doesn't declare the Copilot lane is skipped, not
guessed at.

Run by scripts/bootstrap_agents.sh after it populates .claude/agents/.
Standalone: python scripts/generate_copilot_chatmodes.py
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SRC_DIR = REPO_ROOT / ".claude" / "agents"
OUT_DIR = REPO_ROOT / ".github" / "chatmodes"

# Anchored to the declaration line, but tolerant of where the sentence puts
# its punctuation: definitions write both "**Your lane is Copilot**" and
# "**Your lane is Copilot.**", and a literal match silently skipped two of
# the three Copilot-lane roles.
LANE_PATTERN = re.compile(r"^\*\*Your lane is Copilot", re.M)

# Claude tool grants -> Copilot chat-mode tool names. Several Claude tools
# collapse onto one Copilot tool, which is why this is a set on the way out.
#
# `Agent(...)` has no equivalent: chat modes cannot spawn other chat modes.
# It is dropped rather than approximated, and the dropped grant is reported,
# because silently losing a delegation capability is how an orchestrating
# mode ends up quietly doing the work itself.
TOOL_MAP = {
    "Read": "codebase",
    "Grep": "search",
    "Glob": "search",
    "Edit": "editFiles",
    "Write": "editFiles",
    "Bash": "runCommands",
    "WebSearch": "fetch",
}

# Deliberately no `model:` line is emitted. The chat-mode frontmatter takes a
# model identifier that must match Copilot's picker exactly, and that list
# varies by plan and changes over time -- emitting a wrong one silently breaks
# the mode. The recommendation is documented in the generated header instead,
# where a human reads it and picks from the real list.
MODEL_ADVICE = {
    "sonnet": "Claude Sonnet (1x premium request per prompt)",
    "opus": "the strongest model your plan offers",
    "haiku": "the included base model (0x - unlimited)",
}


def split_frontmatter(text: str) -> tuple[dict[str, str], str]:
    m = re.match(r"^---\n(.*?)\n---\n(.*)$", text, re.S)
    if not m:
        raise ValueError("no frontmatter")
    fm = dict(re.findall(r"^([A-Za-z_]+):\s*(.*)$", m.group(1), re.M))
    return fm, m.group(2)


def map_tools(raw: str) -> tuple[list[str], list[str]]:
    """Return (copilot tools, dropped Claude grants)."""
    # Agent(a, b) contains commas, so peel it off before splitting.
    dropped: list[str] = []
    agent_grants = re.findall(r"Agent\([^)]*\)", raw)
    for g in agent_grants:
        dropped.append(g)
        raw = raw.replace(g, "")

    mapped: set[str] = set()
    for tool in (t.strip() for t in raw.split(",")):
        if not tool:
            continue
        if tool in TOOL_MAP:
            mapped.add(TOOL_MAP[tool])
        else:
            dropped.append(tool)
    return sorted(mapped), dropped


def render(name: str, fm: dict[str, str], body: str) -> tuple[str, list[str]]:
    tools, dropped = map_tools(fm.get("tools", ""))
    advice = MODEL_ADVICE.get(fm.get("model", ""), "a model appropriate to the task")

    header = [
        "---",
        f"description: {fm.get('description', '').strip()}",
        f"tools: [{', '.join(repr(t) for t in tools)}]",
        "---",
        "",
        f"<!-- GENERATED by scripts/generate_copilot_chatmodes.py from the",
        f"     `{name}` agent definition pinned in agents.lock. Do not edit:",
        f"     re-run scripts/bootstrap_agents.sh instead. Gitignored -- the",
        f"     source is proprietary and lives in the private config repo. -->",
        "",
        f"> **Model:** pick {advice} from the model picker.",
    ]
    if dropped:
        header.append(
            f"> **Not available in this lane:** {', '.join(dropped)} — "
            "chat modes cannot delegate to other modes. Where the instructions "
            "below say to hand work to another role, ask the human to switch "
            "modes rather than doing that role's work yourself."
        )
    header += ["", "---", ""]
    return "\n".join(header) + body, dropped


def main() -> int:
    if not SRC_DIR.is_dir():
        print(f"error: {SRC_DIR} not found - run scripts/bootstrap_agents.sh first.",
              file=sys.stderr)
        return 1

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    # Clear stale modes so a role that leaves the Copilot lane stops being
    # offered. The committed README is the one thing preserved.
    for stale in OUT_DIR.glob("*.chatmode.md"):
        stale.unlink()

    written, skipped = [], []
    for src in sorted(SRC_DIR.glob("*.md")):
        if src.name == "README.md":
            continue
        try:
            fm, body = split_frontmatter(src.read_text(encoding="utf-8"))
        except ValueError:
            print(f"warning: {src.name} has no frontmatter, skipping", file=sys.stderr)
            continue

        if not LANE_PATTERN.search(body):
            skipped.append(src.stem)
            continue

        name = fm.get("name", src.stem)
        content, dropped = render(name, fm, body)
        (OUT_DIR / f"{name}.chatmode.md").write_text(content, encoding="utf-8")
        written.append(f"{name}{' (dropped: ' + ', '.join(dropped) + ')' if dropped else ''}")

    for w in written:
        print(f"  chatmode: {w}")
    print(f"Wrote {len(written)} Copilot chat mode(s) to .github/chatmodes/ (gitignored).")
    if skipped:
        print(f"  not in the Copilot lane, skipped: {', '.join(skipped)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
