#!/usr/bin/env python3
"""Render fetched private agent definitions as project-scoped Codex agents."""

from __future__ import annotations

import json
import re
import shutil
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SOURCE_DIR = REPO_ROOT / ".claude" / "agents"
OUTPUT_DIR = REPO_ROOT / ".codex" / "agents"

EXPECTED_ROLES = {
    "architect",
    "builder",
    "notebook-qa",
    "orchestrator",
    "platform",
    "reviewer",
    "scout",
}
READ_ONLY_ROLES = {"reviewer", "scout"}
REASONING_EFFORT = {
    "architect": "high",
    "orchestrator": "high",
    "reviewer": "high",
    "builder": "medium",
    "notebook-qa": "medium",
    "platform": "medium",
    "scout": "low",
}

CODEX_PREAMBLE = """Codex rendering note:
You are running this repository role as a Codex custom subagent. Ignore any
substrate-specific directions below about switching between Claude, Copilot,
or Ollama models. Preserve the role's ownership boundaries, governance rules,
handoff requirements, and completion criteria. Read AGENTS.md before acting.
"""


def split_frontmatter(text: str) -> tuple[dict[str, str], str]:
    match = re.match(r"^---\n(.*?)\n---\n(.*)$", text, re.DOTALL)
    if not match:
        raise ValueError("no frontmatter")
    fields = dict(re.findall(r"^([A-Za-z_]+):\s*(.*)$", match.group(1), re.MULTILINE))
    return fields, match.group(2)


def toml_string(value: str) -> str:
    """Encode a TOML basic string using JSON-compatible escaping."""
    return json.dumps(value, ensure_ascii=False)


def render(fields: dict[str, str], body: str) -> str:
    name = fields["name"]
    instructions = f"{CODEX_PREAMBLE}\n{body.strip()}\n"
    effort = toml_string(REASONING_EFFORT.get(name, "medium"))
    sandbox = "read-only" if name in READ_ONLY_ROLES else "workspace-write"
    return "\n".join(
        [
            "# Generated by scripts/generate_codex_agents.py. Do not edit.",
            f"name = {toml_string(name)}",
            f"description = {toml_string(fields['description'])}",
            f"model_reasoning_effort = {effort}",
            f"sandbox_mode = {toml_string(sandbox)}",
            f"developer_instructions = {toml_string(instructions)}",
            "",
        ]
    )


def main() -> int:
    sources = [
        path for path in sorted(SOURCE_DIR.glob("*.md")) if path.name != "README.md"
    ]
    if not sources:
        print(
            "error: .claude/agents/ is not populated; run "
            "scripts/bootstrap_agents.sh first.",
            file=sys.stderr,
        )
        return 1

    actual_roles = {source.stem for source in sources}
    if actual_roles != EXPECTED_ROLES:
        missing = sorted(EXPECTED_ROLES - actual_roles)
        unexpected = sorted(actual_roles - EXPECTED_ROLES)
        details = []
        if missing:
            details.append(f"missing: {', '.join(missing)}")
        if unexpected:
            details.append(f"unexpected: {', '.join(unexpected)}")
        print(
            "error: fetched agent roster does not match the expected seven roles "
            f"({'; '.join(details)}).",
            file=sys.stderr,
        )
        return 1

    rendered_agents: list[tuple[str, str]] = []
    for source in sources:
        try:
            fields, body = split_frontmatter(source.read_text(encoding="utf-8"))
            name = fields["name"]
            description = fields["description"]
        except (KeyError, ValueError) as exc:
            print(f"error: cannot render {source.name}: {exc}", file=sys.stderr)
            return 1
        if name != source.stem:
            print(
                f"error: {source.name} declares name {name!r}; filename and name "
                "must match.",
                file=sys.stderr,
            )
            return 1
        if not description.strip():
            print(f"error: {source.name} has no description.", file=sys.stderr)
            return 1

        rendered_agents.append((name, render(fields, body)))

    # Validate the complete source set before replacing any known-good output.
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    for stale in OUTPUT_DIR.glob("*.toml"):
        stale.unlink()
    for name, content in rendered_agents:
        (OUTPUT_DIR / f"{name}.toml").write_text(content, encoding="utf-8")

    source_stamp = SOURCE_DIR / ".fetched"
    if source_stamp.exists():
        shutil.copyfile(source_stamp, OUTPUT_DIR / ".fetched")
    else:
        (OUTPUT_DIR / ".fetched").unlink(missing_ok=True)

    written = [name for name, _ in rendered_agents]
    print(f"Wrote {len(written)} Codex agent(s) to .codex/agents/ (gitignored).")
    print(f"  agents: {', '.join(written)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
